// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naardjfueybihuhwjtjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYXJkamZ1ZXliaWh1aHdqdGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDk1NDAsImV4cCI6MjA2NzEyNTU0MH0.9dU_j900a1XfsjVNatvbDX4EHRaBBscYzG9QZv7cYYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});